/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ntsc.cas.cn.avro.difference.oneRound;
@org.apache.avro.specific.AvroGenerated
public enum Duration implements org.apache.avro.generic.GenericEnumSymbol<Duration> {
  _3MIN, _5MIN, _10MIN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Duration\",\"namespace\":\"ntsc.cas.cn.avro.difference.oneRound\",\"symbols\":[\"_3MIN\",\"_5MIN\",\"_10MIN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
